# Generated by Django 2.1 on 2019-07-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('userinput', models.CharField(max_length=200)),
            ],
        ),
    ]
